Problem: we have batch of sparse representation of samples, we need to convert it to dense representation

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.InteractiveSession()

In [4]:
ORIG_N = 4
RES_N = 10
BATCH = 5

In [11]:
batch_idx = np.array([[0, 3, 4, 5], [1, 4, 5, 6], [2, 5, 6, 7], [3, 6, 7, 8], [4, 7, 8, 9]])

In [8]:
batch_val = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])

In [18]:
print batch_idx
print batch_val

[[0 3 4 5]
 [1 4 5 6]
 [2 5 6 7]
 [3 6 7 8]
 [4 7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [13]:
idx_t = tf.placeholder(tf.int32, (None, ORIG_N))
val_t = tf.placeholder(tf.float32, (None, ORIG_N))

In [14]:
flat_val_t = tf.reshape(val_t, (ORIG_N * BATCH,))

In [19]:
flat_val_t.eval({val_t: batch_val})

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.], dtype=float32)

In [20]:
idx_deltas_t = tf.range(0, BATCH*RES_N, RES_N)

In [33]:
flat_idx_t = tf.reshape(idx_t + tf.expand_dims(idx_deltas_t, -1), (ORIG_N * BATCH,))

In [34]:
flat_idx_t.eval({idx_t: batch_idx})

array([ 0,  3,  4,  5, 11, 14, 15, 16, 22, 25, 26, 27, 33, 36, 37, 38, 44,
       47, 48, 49], dtype=int32)

In [37]:
flat_dense_t = tf.sparse_to_dense(flat_idx_t, (RES_N * BATCH,), flat_val_t)

In [38]:
dense_t = tf.reshape(flat_dense_t, (BATCH, RES_N))

In [39]:
dense_t.eval({val_t: batch_val, idx_t: batch_idx})

array([[  1.,   0.,   0.,   2.,   3.,   4.,   0.,   0.,   0.,   0.],
       [  0.,   5.,   0.,   0.,   6.,   7.,   8.,   0.,   0.,   0.],
       [  0.,   0.,   9.,   0.,   0.,  10.,  11.,  12.,   0.,   0.],
       [  0.,   0.,   0.,  13.,   0.,   0.,  14.,  15.,  16.,   0.],
       [  0.,   0.,   0.,   0.,  17.,   0.,   0.,  18.,  19.,  20.]], dtype=float32)